### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by josek5494** [stdavis/OfflineMbTiles#2]
I'm trying to use the constructor for the custom layer but it says to me that it doesnt exist. I have included in my project the js files for the layer and the sqlite plugin. Am i missing something?

Thanks!

**Comment by stdavis** [comment]
I haven't touched this in years so no guarantees that it still works. IIRC it uses some files in my dropbox account that I've probably gotten rid of. If I was looking at this today I would be checking out the Vector Tiles spec.
